import React, { createContext, useContext, useState } from 'react';

const translations = {
    en: {
        dashboard: "Dashboard",
        scanner: "Scanner",
        catalog: "Catalog",
        crm: "Customers",
        dailySales: "Daily Sales",
        revenue: "Revenue",
        addOrder: "Add Order",
        insights: "AI Insights",
        actionPoints: "Action Points",
        products: "Products",
        orders: "Orders",
        welcome: "Welcome back!",
        scanInfo: "Scan manual entry images",
        growingBusiness: "Let's grow your business!",
        hindi: "हिन्दी",
        english: "English",
        inventory: "Inventory Status",
        stockItems: "Stock Items",
        lowStock: "Low Stock",
        salesTrend: "Sales Trend",
        profit: "Profit",
        growthTips: "Growth Tips",
        action1: "Contact 5 regular customers with a personalized offer.",
        action2: "Post a new product photo on WhatsApp status today.",
        action3: "Verify stock of top 3 selling items.",
        action4: "Offer a small discount for orders above ₹500.",
        action5: "Review expenses from yesterday to find saving spots.",
        aiSummary: "Your sales increased by 15% yesterday. Most sales came from your online catalog.",
        insightHeader: "Business Analysis",
        sale: "Sale",
        purchase: "Purchase",
        expense: "Expense",
        sorting: "Sorting Data...",
        detected: "Detected",
        addCustomer: "Add Customer",
        phone: "Phone",
        lastOrder: "Last Order",
        price: "Price",
        stock: "Stock",
        voiceHint: "Tap to talk in Hindi",
        store: "Store",
        inventory: "Inventory",
        invoice: "Invoice",
        billTo: "Bill To",
        item: "Item",
        quantity: "Quantity",
        total: "Total",
        generateInvoice: "Generate Invoice",
        addToCart: "Add to Cart",
        manageStock: "Manage Stock",
        lowStockAlert: "Low Stock Alert!",
        invoiceHeader: "Tax Invoice",
        modern: "Modern",
        classic: "Classic",
        thermal: "Thermal",
        shareWhatsapp: "Share on WhatsApp",
        printThermal: "Print Thermal",
        udyamReg: "Udyam Registration",
        free: "100% Free",
        govtSchemes: "Govt Schemes",
        empowerment: "Services",
        learnMore: "Learn More",
        geminiSettings: "Gemini AI Settings",
        enterApiKey: "Enter Gemini API Key",
        aiTasks: "What the AI can do for you",
        setupProfile: "Setup Your Business Profile",
        setupDesc: "This info helps the AI understand and grow your business.",
        bizName: "Business Name",
        ownerName: "Owner Name",
        bizType: "Business Type",
        city: "City/Town",
        saveProfile: "Start Using App",
        chatWithAi: "Chat with Sudarshan AI",
        typeMessage: "Type your message...",
        aiGreeting: "How can I help you today?",
        suggestSales: "Check Sales",
        suggestStock: "Low Stock Items",
        suggestAdd: "Add new item",
    },
    hi: {
        dashboard: "डैशबोर्ड",
        scanner: "स्कैनर",
        catalog: "प्रोडक्ट लिस्ट",
        crm: "ग्राहक",
        dailySales: "दैनिक बिक्री",
        revenue: "आय",
        addOrder: "ऑर्डर जोड़ें",
        insights: "एआई सुझाव",
        actionPoints: "अगले दिन के कदम",
        products: "उत्पाद",
        orders: "ऑर्डर",
        welcome: "नमस्ते!",
        scanInfo: "मैन्युअल पर्चियों को स्कैन करें",
        growingBusiness: "व्यापार बढ़ाएं!",
        hindi: "हिन्दी",
        english: "English",
        inventory: "स्टॉक की स्थिति",
        stockItems: "स्टॉक में सामान",
        lowStock: "कम स्टॉक",
        salesTrend: "बिक्री का रुझान",
        profit: "मुनाफा",
        growthTips: "विकास के टिप्स",
        action1: "5 नियमित ग्राहकों को व्यक्तिगत ऑफर के साथ संपर्क करें।",
        action2: "आज व्हाट्सएप स्टेटस पर एक नया उत्पाद फोटो पोस्ट करें।",
        action3: "सबसे ज्यादा बिकने वाली 3 वस्तुओं के स्टॉक की जाँच करें।",
        action4: "₹500 से अधिक के ऑर्डर पर छोटी छूट दें।",
        action5: "बचत के स्थान खोजने के लिए कल के खर्चों की समीक्षा करें।",
        aiSummary: "कल आपकी बिक्री में 15% की वृद्धि हुई। ज्यादातर बिक्री आपके ऑनलाइन कैटलॉग से हुई।",
        insightHeader: "व्यापार विश्लेषण",
        sale: "बिक्री",
        purchase: "खरीद",
        expense: "खर्च",
        sorting: "डेटा छाँट रहे हैं...",
        detected: "पहचाना गया",
        addCustomer: "ग्राहक जोड़ें",
        phone: "फोन",
        lastOrder: "पिछला ऑर्डर",
        price: "कीमत",
        stock: "स्टॉक",
        voiceHint: "हिंदी में बात करने के लिए दबाएं",
        store: "स्टोर",
        inventory: "स्टॉक प्रबंधन",
        invoice: "बिल बनाएं",
        billTo: "बिल किसके नाम",
        item: "वस्तु",
        quantity: "मात्रा",
        total: "कुल",
        generateInvoice: "इनवॉइस जनरेट करें",
        addToCart: "कार्ट में जोड़ें",
        manageStock: "स्टॉक अपडेट करें",
        lowStockAlert: "स्टॉक कम है!",
        invoiceHeader: "टैक्स इनवॉइस",
        modern: "आधुनिक",
        classic: "क्लासिक",
        thermal: "थर्मल",
        shareWhatsapp: "व्हाट्सएप पर भेजें",
        printThermal: "थर्मल प्रिंट",
        udyamReg: "उद्यम पंजीकरण",
        free: "100% फ्री",
        govtSchemes: "सरकारी योजनाएं",
        empowerment: "सेवाएं",
        learnMore: "अधिक जानें",
        geminiSettings: "जेमिनी एआई सेटिंग्स",
        enterApiKey: "जेमिनी एआई की दर्ज करें",
        aiTasks: "एआई आपके लिए क्या कर सकता है",
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('hi'); // Default to Hindi as per request

    const t = (key) => translations[lang][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
